export interface CountryOption { name: string; iso: string; flag: string; }

const list: [string, string][] = [
  ["Afghanistan", "af"], ["Albania", "al"], ["American Samoa", "as"], ["Andorra", "ad"],
  ["Angola", "ao"], ["Anguilla", "ai"], ["Antigua And Barbuda", "ag"], ["Argentina", "ar"],
  ["Aruba", "aw"], ["Australia", "au"], ["Austria", "at"], ["Azerbaijan", "az"],
  ["Bahamas", "bs"], ["Bahrain", "bh"], ["Bangladesh", "bd"], ["Barbados", "bb"],
  ["Belgium", "be"], ["Belize", "bz"], ["Benin", "bj"], ["Bermuda", "bm"],
  ["Bhutan", "bt"], ["Bolivia", "bo"], ["Bosnia and Herzegovina", "ba"], ["Botswana", "bw"],
  ["Brazil", "br"], ["British Virgin Islands", "vg"], ["Brunei Darussalam", "bn"], ["Bulgaria", "bg"],
  ["Burkina Faso", "bf"], ["Burundi", "bi"], ["Cambodia", "kh"], ["Cameroon", "cm"],
  ["Canada", "ca"], ["Cape Verde", "cv"], ["Cayman Islands", "ky"], ["Central African Republic", "cf"],
  ["Chad", "td"], ["Chile", "cl"], ["China", "cn"], ["Colombia", "co"],
  ["Comoros", "km"], ["Congo, Democratic Republic of", "cd"], ["Congo-Brazzaville", "cg"], ["Cook Islands", "ck"],
  ["Costa Rica", "cr"], ["Croatia", "hr"], ["Curacao", "cw"], ["Cyprus", "cy"],
  ["Czech Republic", "cz"], ["Denmark", "dk"], ["Djibouti", "dj"], ["Dominica", "dm"],
  ["Dominican Republic", "do"], ["East Timor", "tl"], ["Ecuador", "ec"], ["Egypt", "eg"],
  ["El Salvador", "sv"], ["Equatorial Guinea", "gq"], ["Eritrea", "er"], ["Estonia", "ee"],
  ["Ethiopia", "et"], ["Falkland Islands (Malvinas)", "fk"], ["Fiji", "fj"], ["Finland", "fi"],
  ["France", "fr"], ["French Guiana", "gf"], ["Gabon", "ga"], ["Gambia", "gm"],
  ["Georgia", "ge"], ["Germany", "de"], ["Ghana", "gh"], ["Gibraltar", "gi"],
  ["Greece", "gr"], ["Grenada", "gd"], ["Guadeloupe", "gp"], ["Guam", "gu"],
  ["Guinea", "gn"], ["Guinea-Bissau", "gw"], ["Guyana", "gy"], ["Haiti", "ht"],
  ["Honduras", "hn"], ["Hong Kong", "hk"], ["Hungary", "hu"], ["Iceland", "is"],
  ["India", "in"], ["Indonesia", "id"], ["Iraq", "iq"], ["Ireland", "ie"],
  ["Israel", "il"], ["Italy", "it"], ["Ivory Coast", "ci"], ["Jamaica", "jm"],
  ["Japan", "jp"], ["Jordan", "jo"], ["Kazakhstan", "kz"], ["Kenya", "ke"],
  ["Korea", "kr"], ["Kosovo", "xk"], ["Kuwait", "kw"], ["Kyrghyz Republic", "kg"],
  ["Laos", "la"], ["Latvia", "lv"], ["Lebanon", "lb"], ["Lesotho", "ls"],
  ["Liberia", "lr"], ["Liechtenstein", "li"], ["Lithuania", "lt"], ["Luxembourg", "lu"],
  ["Macau", "mo"], ["Macedonia", "mk"], ["Madagascar", "mg"], ["Malawi", "mw"],
  ["Malaysia", "my"], ["Maldives", "mv"], ["Mali", "ml"], ["Malta", "mt"],
  ["Marshall Islands", "mh"], ["Martinique", "mq"], ["Mauritania", "mr"], ["Mauritius", "mu"],
  ["Mayotte", "yt"], ["Mexico", "mx"], ["Micronesia", "fm"], ["Moldova", "md"],
  ["Mongolia", "mn"], ["Montenegro", "me"], ["Montserrat", "ms"], ["Morocco", "ma"],
  ["Mozambique", "mz"], ["Myanmar", "mm"], ["Namibia", "na"], ["Nauru", "nr"],
  ["Nepal", "np"], ["Netherlands", "nl"], ["New Zealand", "nz"], ["Nicaragua", "ni"],
  ["Niger", "ne"], ["Nigeria", "ng"], ["Niue", "nu"], ["Northern Mariana Islands", "mp"],
  ["Norway", "no"], ["Oman", "om"], ["Pakistan", "pk"], ["Palau", "pw"],
  ["Palestinian Authority", "ps"], ["Panama", "pa"], ["Papua New Guinea", "pg"], ["Paraguay", "py"],
  ["Peru", "pe"], ["Philippines", "ph"], ["Poland", "pl"], ["Portugal", "pt"],
  ["Puerto Rico", "pr"], ["Qatar", "qa"], ["Reunion Island", "re"], ["Romania", "ro"],
  ["Rwanda", "rw"], ["Saint Barthelemy", "bl"], ["Saint Kitts And Nevis", "kn"], ["Saint Lucia", "lc"],
  ["Saint Vincent And The Grenadines", "vc"], ["Samoa", "ws"], ["Saudi Arabia", "sa"], ["Senegal", "sn"],
  ["Serbia", "rs"], ["Seychelles", "sc"], ["Sierra Leone", "sl"], ["Singapore", "sg"],
  ["Slovakia", "sk"], ["Slovenia", "si"], ["Solomon Islands", "sb"], ["South Africa", "za"],
  ["Spain", "es"], ["Sri Lanka", "lk"], ["St. Maarten", "sx"], ["Sudan", "sd"],
  ["Suriname", "sr"], ["Sweden", "se"], ["Switzerland", "ch"], ["Taiwan", "tw"],
  ["Tajikistan", "tj"], ["Tanzania", "tz"], ["Thailand", "th"], ["Togo", "tg"],
  ["Tonga", "to"], ["Trinidad and Tobago", "tt"], ["Tunisia", "tn"], ["Turkey", "tr"],
  ["Turkmenistan", "tm"], ["Turks and Caicos Islands", "tc"], ["Tuvalu", "tv"], ["Uganda", "ug"],
  ["Ukraine", "ua"], ["United Arab Emirates", "ae"], ["United Kingdom", "gb"], ["United States", "us"],
  ["Uruguay", "uy"], ["Uzbekistan", "uz"], ["Vanuatu", "vu"], ["Venezuela", "ve"],
  ["Vietnam", "vn"],
];

export const countries: CountryOption[] = list.map(([name, iso]) => ({
  name,
  iso,
  flag: `/flags/${iso}.png`,
}));
