export interface CurrencyOption { code: string; name: string; flag: string; }

export const currencies: CurrencyOption[] = [
  { code: "MXN", name: "Mexico", flag: "/flags/mx.png" },
  { code: "GTQ", name: "Guatemala", flag: "/flags/gt.png" },
  { code: "PHP", name: "Philippines", flag: "/flags/ph.png" },
  { code: "USD", name: "Philippines", flag: "/flags/ph.png" },
  { code: "INR", name: "India", flag: "/flags/in.png" },
  { code: "COP", name: "Colombia", flag: "/flags/co.png" },
  { code: "USD", name: "United States", flag: "/flags/us.png" },
  { code: "USD", name: "Dominican Republic", flag: "/flags/do.png" },
  { code: "DOP", name: "Dominican Republic", flag: "/flags/do.png" },
  { code: "JMD", name: "Jamaica", flag: "/flags/jm.png" },
  { code: "AFN", name: "Afghanistan", flag: "/flags/af.png" },
  { code: "USD", name: "Afghanistan", flag: "/flags/af.png" },
  { code: "USD", name: "Afghanistan US Military Base", flag: "/flags/us.png" },
  { code: "EUR", name: "Albania", flag: "/flags/al.png" },
  { code: "ALL", name: "Albania", flag: "/flags/al.png" },
  { code: "USD", name: "American Samoa", flag: "/flags/as.png" },
  { code: "EUR", name: "Andorra", flag: "/flags/ad.png" },
  { code: "AOA", name: "Angola", flag: "/flags/ao.png" },
  { code: "XCD", name: "Anguilla", flag: "/flags/ai.png" },
  { code: "USD", name: "Anguilla", flag: "/flags/ai.png" },
  { code: "XCD", name: "Antigua And Barbuda", flag: "/flags/ag.png" },
  { code: "ARS", name: "Argentina", flag: "/flags/ar.png" },
  { code: "AWG", name: "Aruba", flag: "/flags/aw.png" },
  { code: "AUD", name: "Australia", flag: "/flags/au.png" },
  { code: "EUR", name: "Austria", flag: "/flags/at.png" },
  { code: "USD", name: "Azerbaijan", flag: "/flags/az.png" },
  { code: "AZN", name: "Azerbaijan", flag: "/flags/az.png" },
  { code: "BSD", name: "Bahamas", flag: "/flags/bs.png" },
  { code: "BHD", name: "Bahrain", flag: "/flags/bh.png" },
  { code: "BDT", name: "Bangladesh", flag: "/flags/bd.png" },
  { code: "BBD", name: "Barbados", flag: "/flags/bb.png" },
  { code: "EUR", name: "Belgium", flag: "/flags/be.png" },
  { code: "USD", name: "Belgium US Military Base", flag: "/flags/us.png" },
  { code: "BZD", name: "Belize", flag: "/flags/bz.png" },
  { code: "XOF", name: "Benin", flag: "/flags/bj.png" },
  { code: "BMD", name: "Bermuda", flag: "/flags/bm.png" },
  { code: "BTN", name: "Bhutan", flag: "/flags/bt.png" },
  { code: "BOB", name: "Bolivia", flag: "/flags/bo.png" },
  { code: "BAM", name: "Bosnia and Herzegovina", flag: "/flags/ba.png" },
  { code: "BWP", name: "Botswana", flag: "/flags/bw.png" },
  { code: "BRL", name: "Brazil", flag: "/flags/br.png" },
  { code: "USD", name: "British Virgin Islands", flag: "/flags/vg.png" },
  { code: "BND", name: "Brunei Darussalam", flag: "/flags/bn.png" },
  { code: "EUR", name: "Bulgaria", flag: "/flags/bg.png" },
  { code: "XOF", name: "Burkina Faso", flag: "/flags/bf.png" },
  { code: "USD", name: "Burundi", flag: "/flags/bi.png" },
  { code: "BIF", name: "Burundi", flag: "/flags/bi.png" },
  { code: "USD", name: "Cambodia", flag: "/flags/kh.png" },
  { code: "XAF", name: "Cameroon", flag: "/flags/cm.png" },
  { code: "CAD", name: "Canada", flag: "/flags/ca.png" },
  { code: "CVE", name: "Cape Verde", flag: "/flags/cv.png" },
  { code: "KYD", name: "Cayman Islands", flag: "/flags/ky.png" },
  { code: "XAF", name: "Central African Republic", flag: "/flags/cf.png" },
  { code: "XAF", name: "Chad", flag: "/flags/td.png" },
  { code: "CLP", name: "Chile", flag: "/flags/cl.png" },
  { code: "USD", name: "China", flag: "/flags/cn.png" },
  { code: "CNY", name: "China", flag: "/flags/cn.png" },
  { code: "KMF", name: "Comoros", flag: "/flags/km.png" },
  { code: "USD", name: "Congo, Democratic Republic of", flag: "/flags/cd.png" },
  { code: "XAF", name: "Congo-Brazzaville", flag: "/flags/cg.png" },
  { code: "NZD", name: "Cook Islands", flag: "/flags/ck.png" },
  { code: "CRC", name: "Costa Rica", flag: "/flags/cr.png" },
  { code: "USD", name: "Costa Rica", flag: "/flags/cr.png" },
  { code: "EUR", name: "Croatia", flag: "/flags/hr.png" },
  { code: "USD", name: "Cuba US Military Base", flag: "/flags/us.png" },
  { code: "ANG", name: "Curacao", flag: "/flags/cw.png" },
  { code: "EUR", name: "Cyprus", flag: "/flags/cy.png" },
  { code: "USD", name: "Cyprus (Northern)", flag: "/flags/cy.png" },
  { code: "CZK", name: "Czech Republic", flag: "/flags/cz.png" },
  { code: "DKK", name: "Denmark", flag: "/flags/dk.png" },
  { code: "DJF", name: "Djibouti", flag: "/flags/dj.png" },
  { code: "USD", name: "Djibouti US Military Base", flag: "/flags/us.png" },
  { code: "XCD", name: "Dominica", flag: "/flags/dm.png" },
  { code: "USD", name: "East Timor", flag: "/flags/tl.png" },
  { code: "USD", name: "Ecuador", flag: "/flags/ec.png" },
  { code: "USD", name: "Egypt", flag: "/flags/eg.png" },
  { code: "EGP", name: "Egypt", flag: "/flags/eg.png" },
  { code: "EUR", name: "Egypt", flag: "/flags/eg.png" },
  { code: "USD", name: "El Salvador", flag: "/flags/sv.png" },
  { code: "XAF", name: "Equatorial Guinea", flag: "/flags/gq.png" },
  { code: "ERN", name: "Eritrea", flag: "/flags/er.png" },
  { code: "EUR", name: "Estonia", flag: "/flags/ee.png" },
  { code: "ETB", name: "Ethiopia", flag: "/flags/et.png" },
  { code: "USD", name: "Falkland Islands (Malvinas)", flag: "/flags/fk.png" },
  { code: "FKP", name: "Falkland Islands (Malvinas)", flag: "/flags/fk.png" },
  { code: "FJD", name: "Fiji", flag: "/flags/fj.png" },
  { code: "EUR", name: "Finland", flag: "/flags/fi.png" },
  { code: "EUR", name: "France", flag: "/flags/fr.png" },
  { code: "EUR", name: "French Guiana", flag: "/flags/gf.png" },
  { code: "XAF", name: "Gabon", flag: "/flags/ga.png" },
  { code: "GMD", name: "Gambia", flag: "/flags/gm.png" },
  { code: "GEL", name: "Georgia", flag: "/flags/ge.png" },
  { code: "USD", name: "Georgia", flag: "/flags/ge.png" },
  { code: "EUR", name: "Germany", flag: "/flags/de.png" },
  { code: "USD", name: "Germany US Military Base", flag: "/flags/us.png" },
  { code: "GHS", name: "Ghana", flag: "/flags/gh.png" },
  { code: "GBP", name: "Gibraltar", flag: "/flags/gi.png" },
  { code: "EUR", name: "Greece", flag: "/flags/gr.png" },
  { code: "USD", name: "Greece US Military Base", flag: "/flags/us.png" },
  { code: "XCD", name: "Grenada", flag: "/flags/gd.png" },
  { code: "EUR", name: "Guadeloupe", flag: "/flags/gp.png" },
  { code: "USD", name: "Guam", flag: "/flags/gu.png" },
  { code: "USD", name: "Guam US Military Base", flag: "/flags/us.png" },
  { code: "GNF", name: "Guinea", flag: "/flags/gn.png" },
  { code: "XOF", name: "Guinea-Bissau", flag: "/flags/gw.png" },
  { code: "GYD", name: "Guyana", flag: "/flags/gy.png" },
  { code: "USD", name: "Haiti", flag: "/flags/ht.png" },
  { code: "HTG", name: "Haiti", flag: "/flags/ht.png" },
  { code: "HNL", name: "Honduras", flag: "/flags/hn.png" },
  { code: "USD", name: "Honduras US Military Base", flag: "/flags/us.png" },
  { code: "USD", name: "Hong Kong", flag: "/flags/hk.png" },
  { code: "HKD", name: "Hong Kong", flag: "/flags/hk.png" },
  { code: "HUF", name: "Hungary", flag: "/flags/hu.png" },
  { code: "EUR", name: "Iceland", flag: "/flags/is.png" },
  { code: "ISK", name: "Iceland", flag: "/flags/is.png" },
  { code: "IDR", name: "Indonesia", flag: "/flags/id.png" },
  { code: "IQD", name: "Iraq", flag: "/flags/iq.png" },
  { code: "USD", name: "Iraq US Military Base", flag: "/flags/us.png" },
  { code: "EUR", name: "Ireland", flag: "/flags/ie.png" },
  { code: "USD", name: "Israel", flag: "/flags/il.png" },
  { code: "ILS", name: "Israel", flag: "/flags/il.png" },
  { code: "EUR", name: "Italy", flag: "/flags/it.png" },
  { code: "USD", name: "Italy US Military Base", flag: "/flags/us.png" },
  { code: "XOF", name: "Ivory Coast", flag: "/flags/ci.png" },
  { code: "JPY", name: "Japan", flag: "/flags/jp.png" },
  { code: "USD", name: "Japan US Military Base", flag: "/flags/us.png" },
  { code: "JOD", name: "Jordan", flag: "/flags/jo.png" },
  { code: "KZT", name: "Kazakhstan", flag: "/flags/kz.png" },
  { code: "USD", name: "Kazakhstan", flag: "/flags/kz.png" },
  { code: "KES", name: "Kenya", flag: "/flags/ke.png" },
  { code: "USD", name: "Korea", flag: "/flags/kr.png" },
  { code: "KRW", name: "Korea", flag: "/flags/kr.png" },
  { code: "USD", name: "Korea US Military Base", flag: "/flags/us.png" },
  { code: "EUR", name: "Kosovo", flag: "/flags/xk.png" },
  { code: "USD", name: "Kosovo US Military Base", flag: "/flags/us.png" },
  { code: "KWD", name: "Kuwait", flag: "/flags/kw.png" },
  { code: "USD", name: "Kuwait US Military Base", flag: "/flags/us.png" },
  { code: "USD", name: "Kyrghyz Republic", flag: "/flags/kg.png" },
  { code: "LAK", name: "Laos", flag: "/flags/la.png" },
  { code: "EUR", name: "Latvia", flag: "/flags/lv.png" },
  { code: "USD", name: "Lebanon", flag: "/flags/lb.png" },
  { code: "LSL", name: "Lesotho", flag: "/flags/ls.png" },
  { code: "USD", name: "Liberia", flag: "/flags/lr.png" },
  { code: "CHF", name: "Liechtenstein", flag: "/flags/li.png" },
  { code: "EUR", name: "Lithuania", flag: "/flags/lt.png" },
  { code: "EUR", name: "Luxembourg", flag: "/flags/lu.png" },
  { code: "MOP", name: "Macau", flag: "/flags/mo.png" },
  { code: "MKD", name: "Macedonia", flag: "/flags/mk.png" },
  { code: "EUR", name: "Macedonia", flag: "/flags/mk.png" },
  { code: "MGA", name: "Madagascar", flag: "/flags/mg.png" },
  { code: "MWK", name: "Malawi", flag: "/flags/mw.png" },
  { code: "MYR", name: "Malaysia", flag: "/flags/my.png" },
  { code: "MVR", name: "Maldives", flag: "/flags/mv.png" },
  { code: "XOF", name: "Mali", flag: "/flags/ml.png" },
  { code: "EUR", name: "Malta", flag: "/flags/mt.png" },
  { code: "USD", name: "Marshall Islands", flag: "/flags/mh.png" },
  { code: "EUR", name: "Martinique", flag: "/flags/mq.png" },
  { code: "MRU", name: "Mauritania", flag: "/flags/mr.png" },
  { code: "MUR", name: "Mauritius", flag: "/flags/mu.png" },
  { code: "EUR", name: "Mayotte", flag: "/flags/yt.png" },
  { code: "USD", name: "Micronesia", flag: "/flags/fm.png" },
  { code: "EUR", name: "Moldova", flag: "/flags/md.png" },
  { code: "MDL", name: "Moldova", flag: "/flags/md.png" },
  { code: "USD", name: "Moldova", flag: "/flags/md.png" },
  { code: "MNT", name: "Mongolia", flag: "/flags/mn.png" },
  { code: "USD", name: "Mongolia", flag: "/flags/mn.png" },
  { code: "EUR", name: "Montenegro", flag: "/flags/me.png" },
  { code: "XCD", name: "Montserrat", flag: "/flags/ms.png" },
  { code: "MAD", name: "Morocco", flag: "/flags/ma.png" },
  { code: "MZN", name: "Mozambique", flag: "/flags/mz.png" },
  { code: "MMK", name: "Myanmar", flag: "/flags/mm.png" },
  { code: "NAD", name: "Namibia", flag: "/flags/na.png" },
  { code: "AUD", name: "Nauru", flag: "/flags/nr.png" },
  { code: "NPR", name: "Nepal", flag: "/flags/np.png" },
  { code: "EUR", name: "Netherlands", flag: "/flags/nl.png" },
  { code: "USD", name: "Netherlands US Military Base", flag: "/flags/us.png" },
  { code: "NZD", name: "New Zealand", flag: "/flags/nz.png" },
  { code: "USD", name: "Nicaragua", flag: "/flags/ni.png" },
  { code: "XOF", name: "Niger", flag: "/flags/ne.png" },
  { code: "NGN", name: "Nigeria", flag: "/flags/ng.png" },
  { code: "NZD", name: "Niue", flag: "/flags/nu.png" },
  { code: "USD", name: "Northern Mariana Islands", flag: "/flags/mp.png" },
  { code: "NOK", name: "Norway", flag: "/flags/no.png" },
  { code: "OMR", name: "Oman", flag: "/flags/om.png" },
  { code: "PKR", name: "Pakistan", flag: "/flags/pk.png" },
  { code: "USD", name: "Palau", flag: "/flags/pw.png" },
  { code: "ILS", name: "Palestinian Authority", flag: "/flags/ps.png" },
  { code: "JOD", name: "Palestinian Authority", flag: "/flags/ps.png" },
  { code: "USD", name: "Palestinian Authority", flag: "/flags/ps.png" },
  { code: "USD", name: "Panama", flag: "/flags/pa.png" },
  { code: "PGK", name: "Papua New Guinea", flag: "/flags/pg.png" },
  { code: "PYG", name: "Paraguay", flag: "/flags/py.png" },
  { code: "USD", name: "Paraguay", flag: "/flags/py.png" },
  { code: "PEN", name: "Peru", flag: "/flags/pe.png" },
  { code: "USD", name: "Peru", flag: "/flags/pe.png" },
  { code: "PLN", name: "Poland", flag: "/flags/pl.png" },
  { code: "EUR", name: "Portugal", flag: "/flags/pt.png" },
  { code: "USD", name: "Portugal US Military Base", flag: "/flags/us.png" },
  { code: "USD", name: "Puerto Rico", flag: "/flags/pr.png" },
  { code: "QAR", name: "Qatar", flag: "/flags/qa.png" },
  { code: "USD", name: "Qatar US Military Base", flag: "/flags/us.png" },
  { code: "EUR", name: "Reunion Island", flag: "/flags/re.png" },
  { code: "RON", name: "Romania", flag: "/flags/ro.png" },
  { code: "EUR", name: "Romania", flag: "/flags/ro.png" },
  { code: "USD", name: "Rwanda", flag: "/flags/rw.png" },
  { code: "RWF", name: "Rwanda", flag: "/flags/rw.png" },
  { code: "EUR", name: "Saint Barthelemy", flag: "/flags/bl.png" },
  { code: "USD", name: "Saint Kitts And Nevis", flag: "/flags/kn.png" },
  { code: "XCD", name: "Saint Kitts And Nevis", flag: "/flags/kn.png" },
  { code: "XCD", name: "Saint Lucia", flag: "/flags/lc.png" },
  { code: "XCD", name: "Saint Vincent And The Grenadines", flag: "/flags/vc.png" },
  { code: "WST", name: "Samoa", flag: "/flags/ws.png" },
  { code: "SAR", name: "Saudi Arabia", flag: "/flags/sa.png" },
  { code: "XOF", name: "Senegal", flag: "/flags/sn.png" },
  { code: "RSD", name: "Serbia", flag: "/flags/rs.png" },
  { code: "EUR", name: "Serbia", flag: "/flags/rs.png" },
  { code: "SCR", name: "Seychelles", flag: "/flags/sc.png" },
  { code: "SLE", name: "Sierra Leone", flag: "/flags/sl.png" },
  { code: "SGD", name: "Singapore", flag: "/flags/sg.png" },
  { code: "EUR", name: "Slovakia", flag: "/flags/sk.png" },
  { code: "EUR", name: "Slovenia", flag: "/flags/si.png" },
  { code: "SBD", name: "Solomon Islands", flag: "/flags/sb.png" },
  { code: "ZAR", name: "South Africa", flag: "/flags/za.png" },
  { code: "EUR", name: "Spain", flag: "/flags/es.png" },
  { code: "USD", name: "Spain US Military Base", flag: "/flags/us.png" },
  { code: "LKR", name: "Sri Lanka", flag: "/flags/lk.png" },
  { code: "USD", name: "St. Maarten", flag: "/flags/sx.png" },
  { code: "ANG", name: "St. Maarten", flag: "/flags/sx.png" },
  { code: "SDG", name: "Sudan", flag: "/flags/sd.png" },
  { code: "USD", name: "Suriname", flag: "/flags/sr.png" },
  { code: "SEK", name: "Sweden", flag: "/flags/se.png" },
  { code: "CHF", name: "Switzerland", flag: "/flags/ch.png" },
  { code: "USD", name: "Taiwan", flag: "/flags/tw.png" },
  { code: "USD", name: "Tajikistan", flag: "/flags/tj.png" },
  { code: "TZS", name: "Tanzania", flag: "/flags/tz.png" },
  { code: "THB", name: "Thailand", flag: "/flags/th.png" },
  { code: "XOF", name: "Togo", flag: "/flags/tg.png" },
  { code: "TOP", name: "Tonga", flag: "/flags/to.png" },
  { code: "TTD", name: "Trinidad and Tobago", flag: "/flags/tt.png" },
  { code: "TND", name: "Tunisia", flag: "/flags/tn.png" },
  { code: "USD", name: "Turkey", flag: "/flags/tr.png" },
  { code: "TRY", name: "Turkey", flag: "/flags/tr.png" },
  { code: "USD", name: "Turkey US Military Base", flag: "/flags/us.png" },
  { code: "USD", name: "Turkmenistan", flag: "/flags/tm.png" },
  { code: "USD", name: "Turks and Caicos Islands", flag: "/flags/tc.png" },
  { code: "AUD", name: "Tuvalu", flag: "/flags/tv.png" },
  { code: "UGX", name: "Uganda", flag: "/flags/ug.png" },
  { code: "USD", name: "Ukraine", flag: "/flags/ua.png" },
  { code: "UAH", name: "Ukraine", flag: "/flags/ua.png" },
  { code: "AED", name: "United Arab Emirates", flag: "/flags/ae.png" },
  { code: "GBP", name: "United Kingdom", flag: "/flags/gb.png" },
  { code: "USD", name: "United Kingdom US Military Base", flag: "/flags/us.png" },
  { code: "USD", name: "Uruguay", flag: "/flags/uy.png" },
  { code: "UYU", name: "Uruguay", flag: "/flags/uy.png" },
  { code: "USD", name: "Uzbekistan", flag: "/flags/uz.png" },
  { code: "VUV", name: "Vanuatu", flag: "/flags/vu.png" },
  { code: "VEF", name: "Venezuela", flag: "/flags/ve.png" },
  { code: "VND", name: "Vietnam", flag: "/flags/vn.png" },
  { code: "USD", name: "Vietnam", flag: "/flags/vn.png" },
  { code: "USD", name: "Virgin Islands (US)", flag: "/flags/vi.png" },
  { code: "USD", name: "Yemen", flag: "/flags/ye.png" },
  { code: "ZMW", name: "Zambia", flag: "/flags/zm.png" },
  { code: "USD", name: "Zimbabwe", flag: "/flags/zw.png" },
];
