export interface CurrencyOption { code: string; name: string; flag: string; }

export const currencies: CurrencyOption[] = [
  { code: "MXN", name: "Mexico", flag: "https://flagcdn.com/w80/mx.png" },
  { code: "GTQ", name: "Guatemala", flag: "https://flagcdn.com/w80/gt.png" },
  { code: "PHP", name: "Philippines", flag: "https://flagcdn.com/w80/ph.png" },
  { code: "USD", name: "Philippines", flag: "https://flagcdn.com/w80/ph.png" },
  { code: "INR", name: "India", flag: "https://flagcdn.com/w80/in.png" },
  { code: "COP", name: "Colombia", flag: "https://flagcdn.com/w80/co.png" },
  { code: "USD", name: "United States", flag: "https://flagcdn.com/w80/us.png" },
  { code: "USD", name: "Dominican Republic", flag: "https://flagcdn.com/w80/do.png" },
  { code: "DOP", name: "Dominican Republic", flag: "https://flagcdn.com/w80/do.png" },
  { code: "JMD", name: "Jamaica", flag: "https://flagcdn.com/w80/jm.png" },
  { code: "AFN", name: "Afghanistan", flag: "https://flagcdn.com/w80/af.png" },
  { code: "USD", name: "Afghanistan", flag: "https://flagcdn.com/w80/af.png" },
  { code: "USD", name: "Afghanistan US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "EUR", name: "Albania", flag: "https://flagcdn.com/w80/al.png" },
  { code: "ALL", name: "Albania", flag: "https://flagcdn.com/w80/al.png" },
  { code: "USD", name: "American Samoa", flag: "https://flagcdn.com/w80/as.png" },
  { code: "EUR", name: "Andorra", flag: "https://flagcdn.com/w80/ad.png" },
  { code: "AOA", name: "Angola", flag: "https://flagcdn.com/w80/ao.png" },
  { code: "XCD", name: "Anguilla", flag: "https://flagcdn.com/w80/ai.png" },
  { code: "USD", name: "Anguilla", flag: "https://flagcdn.com/w80/ai.png" },
  { code: "XCD", name: "Antigua And Barbuda", flag: "https://flagcdn.com/w80/ag.png" },
  { code: "ARS", name: "Argentina", flag: "https://flagcdn.com/w80/ar.png" },
  { code: "AWG", name: "Aruba", flag: "https://flagcdn.com/w80/aw.png" },
  { code: "AUD", name: "Australia", flag: "https://flagcdn.com/w80/au.png" },
  { code: "EUR", name: "Austria", flag: "https://flagcdn.com/w80/at.png" },
  { code: "USD", name: "Azerbaijan", flag: "https://flagcdn.com/w80/az.png" },
  { code: "AZN", name: "Azerbaijan", flag: "https://flagcdn.com/w80/az.png" },
  { code: "BSD", name: "Bahamas", flag: "https://flagcdn.com/w80/bs.png" },
  { code: "BHD", name: "Bahrain", flag: "https://flagcdn.com/w80/bh.png" },
  { code: "BDT", name: "Bangladesh", flag: "https://flagcdn.com/w80/bd.png" },
  { code: "BBD", name: "Barbados", flag: "https://flagcdn.com/w80/bb.png" },
  { code: "EUR", name: "Belgium", flag: "https://flagcdn.com/w80/be.png" },
  { code: "USD", name: "Belgium US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "BZD", name: "Belize", flag: "https://flagcdn.com/w80/bz.png" },
  { code: "XOF", name: "Benin", flag: "https://flagcdn.com/w80/bj.png" },
  { code: "BMD", name: "Bermuda", flag: "https://flagcdn.com/w80/bm.png" },
  { code: "BTN", name: "Bhutan", flag: "https://flagcdn.com/w80/bt.png" },
  { code: "BOB", name: "Bolivia", flag: "https://flagcdn.com/w80/bo.png" },
  { code: "BAM", name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w80/ba.png" },
  { code: "BWP", name: "Botswana", flag: "https://flagcdn.com/w80/bw.png" },
  { code: "BRL", name: "Brazil", flag: "https://flagcdn.com/w80/br.png" },
  { code: "USD", name: "British Virgin Islands", flag: "https://flagcdn.com/w80/vg.png" },
  { code: "BND", name: "Brunei Darussalam", flag: "https://flagcdn.com/w80/bn.png" },
  { code: "EUR", name: "Bulgaria", flag: "https://flagcdn.com/w80/bg.png" },
  { code: "XOF", name: "Burkina Faso", flag: "https://flagcdn.com/w80/bf.png" },
  { code: "USD", name: "Burundi", flag: "https://flagcdn.com/w80/bi.png" },
  { code: "BIF", name: "Burundi", flag: "https://flagcdn.com/w80/bi.png" },
  { code: "USD", name: "Cambodia", flag: "https://flagcdn.com/w80/kh.png" },
  { code: "XAF", name: "Cameroon", flag: "https://flagcdn.com/w80/cm.png" },
  { code: "CAD", name: "Canada", flag: "https://flagcdn.com/w80/ca.png" },
  { code: "CVE", name: "Cape Verde", flag: "https://flagcdn.com/w80/cv.png" },
  { code: "KYD", name: "Cayman Islands", flag: "https://flagcdn.com/w80/ky.png" },
  { code: "XAF", name: "Central African Republic", flag: "https://flagcdn.com/w80/cf.png" },
  { code: "XAF", name: "Chad", flag: "https://flagcdn.com/w80/td.png" },
  { code: "CLP", name: "Chile", flag: "https://flagcdn.com/w80/cl.png" },
  { code: "USD", name: "China", flag: "https://flagcdn.com/w80/cn.png" },
  { code: "CNY", name: "China", flag: "https://flagcdn.com/w80/cn.png" },
  { code: "KMF", name: "Comoros", flag: "https://flagcdn.com/w80/km.png" },
  { code: "USD", name: "Congo, Democratic Republic of", flag: "https://flagcdn.com/w80/cd.png" },
  { code: "XAF", name: "Congo-Brazzaville", flag: "https://flagcdn.com/w80/cg.png" },
  { code: "NZD", name: "Cook Islands", flag: "https://flagcdn.com/w80/ck.png" },
  { code: "CRC", name: "Costa Rica", flag: "https://flagcdn.com/w80/cr.png" },
  { code: "USD", name: "Costa Rica", flag: "https://flagcdn.com/w80/cr.png" },
  { code: "EUR", name: "Croatia", flag: "https://flagcdn.com/w80/hr.png" },
  { code: "USD", name: "Cuba US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "ANG", name: "Curacao", flag: "https://flagcdn.com/w80/cw.png" },
  { code: "EUR", name: "Cyprus", flag: "https://flagcdn.com/w80/cy.png" },
  { code: "USD", name: "Cyprus (Northern)", flag: "https://flagcdn.com/w80/cy.png" },
  { code: "CZK", name: "Czech Republic", flag: "https://flagcdn.com/w80/cz.png" },
  { code: "DKK", name: "Denmark", flag: "https://flagcdn.com/w80/dk.png" },
  { code: "DJF", name: "Djibouti", flag: "https://flagcdn.com/w80/dj.png" },
  { code: "USD", name: "Djibouti US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "XCD", name: "Dominica", flag: "https://flagcdn.com/w80/dm.png" },
  { code: "USD", name: "East Timor", flag: "https://flagcdn.com/w80/tl.png" },
  { code: "USD", name: "Ecuador", flag: "https://flagcdn.com/w80/ec.png" },
  { code: "USD", name: "Egypt", flag: "https://flagcdn.com/w80/eg.png" },
  { code: "EGP", name: "Egypt", flag: "https://flagcdn.com/w80/eg.png" },
  { code: "EUR", name: "Egypt", flag: "https://flagcdn.com/w80/eg.png" },
  { code: "USD", name: "El Salvador", flag: "https://flagcdn.com/w80/sv.png" },
  { code: "XAF", name: "Equatorial Guinea", flag: "https://flagcdn.com/w80/gq.png" },
  { code: "ERN", name: "Eritrea", flag: "https://flagcdn.com/w80/er.png" },
  { code: "EUR", name: "Estonia", flag: "https://flagcdn.com/w80/ee.png" },
  { code: "ETB", name: "Ethiopia", flag: "https://flagcdn.com/w80/et.png" },
  { code: "USD", name: "Falkland Islands (Malvinas)", flag: "https://flagcdn.com/w80/fk.png" },
  { code: "FKP", name: "Falkland Islands (Malvinas)", flag: "https://flagcdn.com/w80/fk.png" },
  { code: "FJD", name: "Fiji", flag: "https://flagcdn.com/w80/fj.png" },
  { code: "EUR", name: "Finland", flag: "https://flagcdn.com/w80/fi.png" },
  { code: "EUR", name: "France", flag: "https://flagcdn.com/w80/fr.png" },
  { code: "EUR", name: "French Guiana", flag: "https://flagcdn.com/w80/gf.png" },
  { code: "XAF", name: "Gabon", flag: "https://flagcdn.com/w80/ga.png" },
  { code: "GMD", name: "Gambia", flag: "https://flagcdn.com/w80/gm.png" },
  { code: "GEL", name: "Georgia", flag: "https://flagcdn.com/w80/ge.png" },
  { code: "USD", name: "Georgia", flag: "https://flagcdn.com/w80/ge.png" },
  { code: "EUR", name: "Germany", flag: "https://flagcdn.com/w80/de.png" },
  { code: "USD", name: "Germany US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "GHS", name: "Ghana", flag: "https://flagcdn.com/w80/gh.png" },
  { code: "GBP", name: "Gibraltar", flag: "https://flagcdn.com/w80/gi.png" },
  { code: "EUR", name: "Greece", flag: "https://flagcdn.com/w80/gr.png" },
  { code: "USD", name: "Greece US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "XCD", name: "Grenada", flag: "https://flagcdn.com/w80/gd.png" },
  { code: "EUR", name: "Guadeloupe", flag: "https://flagcdn.com/w80/gp.png" },
  { code: "USD", name: "Guam", flag: "https://flagcdn.com/w80/gu.png" },
  { code: "USD", name: "Guam US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "GNF", name: "Guinea", flag: "https://flagcdn.com/w80/gn.png" },
  { code: "XOF", name: "Guinea-Bissau", flag: "https://flagcdn.com/w80/gw.png" },
  { code: "GYD", name: "Guyana", flag: "https://flagcdn.com/w80/gy.png" },
  { code: "USD", name: "Haiti", flag: "https://flagcdn.com/w80/ht.png" },
  { code: "HTG", name: "Haiti", flag: "https://flagcdn.com/w80/ht.png" },
  { code: "HNL", name: "Honduras", flag: "https://flagcdn.com/w80/hn.png" },
  { code: "USD", name: "Honduras US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "USD", name: "Hong Kong", flag: "https://flagcdn.com/w80/hk.png" },
  { code: "HKD", name: "Hong Kong", flag: "https://flagcdn.com/w80/hk.png" },
  { code: "HUF", name: "Hungary", flag: "https://flagcdn.com/w80/hu.png" },
  { code: "EUR", name: "Iceland", flag: "https://flagcdn.com/w80/is.png" },
  { code: "ISK", name: "Iceland", flag: "https://flagcdn.com/w80/is.png" },
  { code: "IDR", name: "Indonesia", flag: "https://flagcdn.com/w80/id.png" },
  { code: "IQD", name: "Iraq", flag: "https://flagcdn.com/w80/iq.png" },
  { code: "USD", name: "Iraq US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "EUR", name: "Ireland", flag: "https://flagcdn.com/w80/ie.png" },
  { code: "USD", name: "Israel", flag: "https://flagcdn.com/w80/il.png" },
  { code: "ILS", name: "Israel", flag: "https://flagcdn.com/w80/il.png" },
  { code: "EUR", name: "Italy", flag: "https://flagcdn.com/w80/it.png" },
  { code: "USD", name: "Italy US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "XOF", name: "Ivory Coast", flag: "https://flagcdn.com/w80/ci.png" },
  { code: "JPY", name: "Japan", flag: "https://flagcdn.com/w80/jp.png" },
  { code: "USD", name: "Japan US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "JOD", name: "Jordan", flag: "https://flagcdn.com/w80/jo.png" },
  { code: "KZT", name: "Kazakhstan", flag: "https://flagcdn.com/w80/kz.png" },
  { code: "USD", name: "Kazakhstan", flag: "https://flagcdn.com/w80/kz.png" },
  { code: "KES", name: "Kenya", flag: "https://flagcdn.com/w80/ke.png" },
  { code: "USD", name: "Korea", flag: "https://flagcdn.com/w80/kr.png" },
  { code: "KRW", name: "Korea", flag: "https://flagcdn.com/w80/kr.png" },
  { code: "USD", name: "Korea US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "EUR", name: "Kosovo", flag: "https://flagcdn.com/w80/xk.png" },
  { code: "USD", name: "Kosovo US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "KWD", name: "Kuwait", flag: "https://flagcdn.com/w80/kw.png" },
  { code: "USD", name: "Kuwait US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "USD", name: "Kyrghyz Republic", flag: "https://flagcdn.com/w80/kg.png" },
  { code: "LAK", name: "Laos", flag: "https://flagcdn.com/w80/la.png" },
  { code: "EUR", name: "Latvia", flag: "https://flagcdn.com/w80/lv.png" },
  { code: "USD", name: "Lebanon", flag: "https://flagcdn.com/w80/lb.png" },
  { code: "LSL", name: "Lesotho", flag: "https://flagcdn.com/w80/ls.png" },
  { code: "USD", name: "Liberia", flag: "https://flagcdn.com/w80/lr.png" },
  { code: "CHF", name: "Liechtenstein", flag: "https://flagcdn.com/w80/li.png" },
  { code: "EUR", name: "Lithuania", flag: "https://flagcdn.com/w80/lt.png" },
  { code: "EUR", name: "Luxembourg", flag: "https://flagcdn.com/w80/lu.png" },
  { code: "MOP", name: "Macau", flag: "https://flagcdn.com/w80/mo.png" },
  { code: "MKD", name: "Macedonia", flag: "https://flagcdn.com/w80/mk.png" },
  { code: "EUR", name: "Macedonia", flag: "https://flagcdn.com/w80/mk.png" },
  { code: "MGA", name: "Madagascar", flag: "https://flagcdn.com/w80/mg.png" },
  { code: "MWK", name: "Malawi", flag: "https://flagcdn.com/w80/mw.png" },
  { code: "MYR", name: "Malaysia", flag: "https://flagcdn.com/w80/my.png" },
  { code: "MVR", name: "Maldives", flag: "https://flagcdn.com/w80/mv.png" },
  { code: "XOF", name: "Mali", flag: "https://flagcdn.com/w80/ml.png" },
  { code: "EUR", name: "Malta", flag: "https://flagcdn.com/w80/mt.png" },
  { code: "USD", name: "Marshall Islands", flag: "https://flagcdn.com/w80/mh.png" },
  { code: "EUR", name: "Martinique", flag: "https://flagcdn.com/w80/mq.png" },
  { code: "MRU", name: "Mauritania", flag: "https://flagcdn.com/w80/mr.png" },
  { code: "MUR", name: "Mauritius", flag: "https://flagcdn.com/w80/mu.png" },
  { code: "EUR", name: "Mayotte", flag: "https://flagcdn.com/w80/yt.png" },
  { code: "USD", name: "Micronesia", flag: "https://flagcdn.com/w80/fm.png" },
  { code: "EUR", name: "Moldova", flag: "https://flagcdn.com/w80/md.png" },
  { code: "MDL", name: "Moldova", flag: "https://flagcdn.com/w80/md.png" },
  { code: "USD", name: "Moldova", flag: "https://flagcdn.com/w80/md.png" },
  { code: "MNT", name: "Mongolia", flag: "https://flagcdn.com/w80/mn.png" },
  { code: "USD", name: "Mongolia", flag: "https://flagcdn.com/w80/mn.png" },
  { code: "EUR", name: "Montenegro", flag: "https://flagcdn.com/w80/me.png" },
  { code: "XCD", name: "Montserrat", flag: "https://flagcdn.com/w80/ms.png" },
  { code: "MAD", name: "Morocco", flag: "https://flagcdn.com/w80/ma.png" },
  { code: "MZN", name: "Mozambique", flag: "https://flagcdn.com/w80/mz.png" },
  { code: "MMK", name: "Myanmar", flag: "https://flagcdn.com/w80/mm.png" },
  { code: "NAD", name: "Namibia", flag: "https://flagcdn.com/w80/na.png" },
  { code: "AUD", name: "Nauru", flag: "https://flagcdn.com/w80/nr.png" },
  { code: "NPR", name: "Nepal", flag: "https://flagcdn.com/w80/np.png" },
  { code: "EUR", name: "Netherlands", flag: "https://flagcdn.com/w80/nl.png" },
  { code: "USD", name: "Netherlands US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "NZD", name: "New Zealand", flag: "https://flagcdn.com/w80/nz.png" },
  { code: "USD", name: "Nicaragua", flag: "https://flagcdn.com/w80/ni.png" },
  { code: "XOF", name: "Niger", flag: "https://flagcdn.com/w80/ne.png" },
  { code: "NGN", name: "Nigeria", flag: "https://flagcdn.com/w80/ng.png" },
  { code: "NZD", name: "Niue", flag: "https://flagcdn.com/w80/nu.png" },
  { code: "USD", name: "Northern Mariana Islands", flag: "https://flagcdn.com/w80/mp.png" },
  { code: "NOK", name: "Norway", flag: "https://flagcdn.com/w80/no.png" },
  { code: "OMR", name: "Oman", flag: "https://flagcdn.com/w80/om.png" },
  { code: "PKR", name: "Pakistan", flag: "https://flagcdn.com/w80/pk.png" },
  { code: "USD", name: "Palau", flag: "https://flagcdn.com/w80/pw.png" },
  { code: "ILS", name: "Palestinian Authority", flag: "https://flagcdn.com/w80/ps.png" },
  { code: "JOD", name: "Palestinian Authority", flag: "https://flagcdn.com/w80/ps.png" },
  { code: "USD", name: "Palestinian Authority", flag: "https://flagcdn.com/w80/ps.png" },
  { code: "USD", name: "Panama", flag: "https://flagcdn.com/w80/pa.png" },
  { code: "PGK", name: "Papua New Guinea", flag: "https://flagcdn.com/w80/pg.png" },
  { code: "PYG", name: "Paraguay", flag: "https://flagcdn.com/w80/py.png" },
  { code: "USD", name: "Paraguay", flag: "https://flagcdn.com/w80/py.png" },
  { code: "PEN", name: "Peru", flag: "https://flagcdn.com/w80/pe.png" },
  { code: "USD", name: "Peru", flag: "https://flagcdn.com/w80/pe.png" },
  { code: "PLN", name: "Poland", flag: "https://flagcdn.com/w80/pl.png" },
  { code: "EUR", name: "Portugal", flag: "https://flagcdn.com/w80/pt.png" },
  { code: "USD", name: "Portugal US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "USD", name: "Puerto Rico", flag: "https://flagcdn.com/w80/pr.png" },
  { code: "QAR", name: "Qatar", flag: "https://flagcdn.com/w80/qa.png" },
  { code: "USD", name: "Qatar US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "EUR", name: "Reunion Island", flag: "https://flagcdn.com/w80/re.png" },
  { code: "RON", name: "Romania", flag: "https://flagcdn.com/w80/ro.png" },
  { code: "EUR", name: "Romania", flag: "https://flagcdn.com/w80/ro.png" },
  { code: "USD", name: "Rwanda", flag: "https://flagcdn.com/w80/rw.png" },
  { code: "RWF", name: "Rwanda", flag: "https://flagcdn.com/w80/rw.png" },
  { code: "EUR", name: "Saint Barthelemy", flag: "https://flagcdn.com/w80/bl.png" },
  { code: "USD", name: "Saint Kitts And Nevis", flag: "https://flagcdn.com/w80/kn.png" },
  { code: "XCD", name: "Saint Kitts And Nevis", flag: "https://flagcdn.com/w80/kn.png" },
  { code: "XCD", name: "Saint Lucia", flag: "https://flagcdn.com/w80/lc.png" },
  { code: "XCD", name: "Saint Vincent And The Grenadines", flag: "https://flagcdn.com/w80/vc.png" },
  { code: "WST", name: "Samoa", flag: "https://flagcdn.com/w80/ws.png" },
  { code: "SAR", name: "Saudi Arabia", flag: "https://flagcdn.com/w80/sa.png" },
  { code: "XOF", name: "Senegal", flag: "https://flagcdn.com/w80/sn.png" },
  { code: "RSD", name: "Serbia", flag: "https://flagcdn.com/w80/rs.png" },
  { code: "EUR", name: "Serbia", flag: "https://flagcdn.com/w80/rs.png" },
  { code: "SCR", name: "Seychelles", flag: "https://flagcdn.com/w80/sc.png" },
  { code: "SLE", name: "Sierra Leone", flag: "https://flagcdn.com/w80/sl.png" },
  { code: "SGD", name: "Singapore", flag: "https://flagcdn.com/w80/sg.png" },
  { code: "EUR", name: "Slovakia", flag: "https://flagcdn.com/w80/sk.png" },
  { code: "EUR", name: "Slovenia", flag: "https://flagcdn.com/w80/si.png" },
  { code: "SBD", name: "Solomon Islands", flag: "https://flagcdn.com/w80/sb.png" },
  { code: "ZAR", name: "South Africa", flag: "https://flagcdn.com/w80/za.png" },
  { code: "EUR", name: "Spain", flag: "https://flagcdn.com/w80/es.png" },
  { code: "USD", name: "Spain US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "LKR", name: "Sri Lanka", flag: "https://flagcdn.com/w80/lk.png" },
  { code: "USD", name: "St. Maarten", flag: "https://flagcdn.com/w80/sx.png" },
  { code: "ANG", name: "St. Maarten", flag: "https://flagcdn.com/w80/sx.png" },
  { code: "SDG", name: "Sudan", flag: "https://flagcdn.com/w80/sd.png" },
  { code: "USD", name: "Suriname", flag: "https://flagcdn.com/w80/sr.png" },
  { code: "SEK", name: "Sweden", flag: "https://flagcdn.com/w80/se.png" },
  { code: "CHF", name: "Switzerland", flag: "https://flagcdn.com/w80/ch.png" },
  { code: "USD", name: "Taiwan", flag: "https://flagcdn.com/w80/tw.png" },
  { code: "USD", name: "Tajikistan", flag: "https://flagcdn.com/w80/tj.png" },
  { code: "TZS", name: "Tanzania", flag: "https://flagcdn.com/w80/tz.png" },
  { code: "THB", name: "Thailand", flag: "https://flagcdn.com/w80/th.png" },
  { code: "XOF", name: "Togo", flag: "https://flagcdn.com/w80/tg.png" },
  { code: "TOP", name: "Tonga", flag: "https://flagcdn.com/w80/to.png" },
  { code: "TTD", name: "Trinidad and Tobago", flag: "https://flagcdn.com/w80/tt.png" },
  { code: "TND", name: "Tunisia", flag: "https://flagcdn.com/w80/tn.png" },
  { code: "USD", name: "Turkey", flag: "https://flagcdn.com/w80/tr.png" },
  { code: "TRY", name: "Turkey", flag: "https://flagcdn.com/w80/tr.png" },
  { code: "USD", name: "Turkey US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "USD", name: "Turkmenistan", flag: "https://flagcdn.com/w80/tm.png" },
  { code: "USD", name: "Turks and Caicos Islands", flag: "https://flagcdn.com/w80/tc.png" },
  { code: "AUD", name: "Tuvalu", flag: "https://flagcdn.com/w80/tv.png" },
  { code: "UGX", name: "Uganda", flag: "https://flagcdn.com/w80/ug.png" },
  { code: "USD", name: "Ukraine", flag: "https://flagcdn.com/w80/ua.png" },
  { code: "UAH", name: "Ukraine", flag: "https://flagcdn.com/w80/ua.png" },
  { code: "AED", name: "United Arab Emirates", flag: "https://flagcdn.com/w80/ae.png" },
  { code: "GBP", name: "United Kingdom", flag: "https://flagcdn.com/w80/gb.png" },
  { code: "USD", name: "United Kingdom US Military Base", flag: "https://flagcdn.com/w80/us.png" },
  { code: "USD", name: "Uruguay", flag: "https://flagcdn.com/w80/uy.png" },
  { code: "UYU", name: "Uruguay", flag: "https://flagcdn.com/w80/uy.png" },
  { code: "USD", name: "Uzbekistan", flag: "https://flagcdn.com/w80/uz.png" },
  { code: "VUV", name: "Vanuatu", flag: "https://flagcdn.com/w80/vu.png" },
  { code: "VEF", name: "Venezuela", flag: "https://flagcdn.com/w80/ve.png" },
  { code: "VND", name: "Vietnam", flag: "https://flagcdn.com/w80/vn.png" },
  { code: "USD", name: "Vietnam", flag: "https://flagcdn.com/w80/vn.png" },
  { code: "USD", name: "Virgin Islands (US)", flag: "https://flagcdn.com/w80/vi.png" },
  { code: "USD", name: "Yemen", flag: "https://flagcdn.com/w80/ye.png" },
  { code: "ZMW", name: "Zambia", flag: "https://flagcdn.com/w80/zm.png" },
  { code: "USD", name: "Zimbabwe", flag: "https://flagcdn.com/w80/zw.png" },
];
