/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTransferRouteImport } from './routes/track-transfer'
import { Route as EcoencyptAdminIndexRouteImport } from './routes/ecoencypt/admin/index'
import { Route as EcoencyptAdminLoginRouteImport } from './routes/ecoencypt/admin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTransferRoute = TrackTransferRouteImport.update({
  id: '/track-transfer',
  path: '/track-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoencyptAdminIndexRoute = EcoencyptAdminIndexRouteImport.update({
  id: '/ecoencypt/admin/',
  path: '/ecoencypt/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoencyptAdminLoginRoute = EcoencyptAdminLoginRouteImport.update({
  id: '/ecoencypt/admin/login',
  path: '/ecoencypt/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/track-transfer': typeof TrackTransferRoute
  '/ecoencypt/admin/login': typeof EcoencyptAdminLoginRoute
  '/ecoencypt/admin/': typeof EcoencyptAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/track-transfer': typeof TrackTransferRoute
  '/ecoencypt/admin/login': typeof EcoencyptAdminLoginRoute
  '/ecoencypt/admin': typeof EcoencyptAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/track-transfer': typeof TrackTransferRoute
  '/ecoencypt/admin/login': typeof EcoencyptAdminLoginRoute
  '/ecoencypt/admin/': typeof EcoencyptAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/track-transfer' | '/ecoencypt/admin/login' | '/ecoencypt/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/track-transfer' | '/ecoencypt/admin/login' | '/ecoencypt/admin'
  id:
    | '__root__'
    | '/'
    | '/track-transfer'
    | '/ecoencypt/admin/login'
    | '/ecoencypt/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrackTransferRoute: typeof TrackTransferRoute
  EcoencyptAdminLoginRoute: typeof EcoencyptAdminLoginRoute
  EcoencyptAdminIndexRoute: typeof EcoencyptAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-transfer': {
      id: '/track-transfer'
      path: '/track-transfer'
      fullPath: '/track-transfer'
      preLoaderRoute: typeof TrackTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecoencypt/admin/': {
      id: '/ecoencypt/admin/'
      path: '/ecoencypt/admin'
      fullPath: '/ecoencypt/admin/'
      preLoaderRoute: typeof EcoencyptAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecoencypt/admin/login': {
      id: '/ecoencypt/admin/login'
      path: '/ecoencypt/admin/login'
      fullPath: '/ecoencypt/admin/login'
      preLoaderRoute: typeof EcoencyptAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrackTransferRoute: TrackTransferRoute,
  EcoencyptAdminLoginRoute: EcoencyptAdminLoginRoute,
  EcoencyptAdminIndexRoute: EcoencyptAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
